[project]
name = "autossh"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sylens Wong <qiumin14@163.com>"]
channels = ["conda-forge"]
platforms = ["linux-aarch64"]

[tasks]

[dependencies]
make = ">=4.4.1,<5"
gcc = ">=14.1.0,<15"
