[project]
name = "Multi-Omics Analysis Enviroments"
version = "0.1"
description = "Multi-Omics Analysis Enviroments"
authors = ["Sylens Wong"]
channels = ["conda-forge", "bioconda", "HCC"]
platforms = ["linux-64"]

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[environments]
wes = ["qc", "wes", "r_base"]
rnaseq = ["qc", "rnaseq", "r_base"]
dipseq = ["qc", "dipseq"]
common = ["common"]
pydata = ["python3_base", "data_science_py"]

[feature.python3_base.dependencies]
python = "3.11.*"
pip = "*"
jupyter = "*"
ipykernel = "*"

[feature.r_base.dependencies]
r-base = "4.2.*"
r-irkernel = "*"
r-remotes = "*"
r-devtools = "*"
r-ggplot2 = "*"
r-ggpubr = "*"
jupyter = "*"

[feature.data_science_py.dependencies]
numpy = "*"
pandas = "*"
statsmodels = "*" # 统计模块
scipy = "*"

[feature.qc.dependencies]
# 质控
fastqc = "*"
fastp = "*"
multiqc = "*"

[feature.wes.dependencies]
# 比对
bwa = "*"
# 多功能
samtools = "*"
bedtools = "*"
# 突变相关
bcftools = "*"
gatk4 = "*"
ensembl-vep = "*"
snpeff = "*"
# CNV检测
CNVkit = "*"
gistic2 = { version = "*", channel = "HCC" }
# 下游展示
bioconductor-maftools = "*"
# MutSig2CV
mcr = { version = "*", channel = "HCC" }

[feature.rnaseq.dependencies]
# 比对
star = "*"
hisat2 = "*"
# 表达矩阵
htseq = "*"
subread = "*"
# 差异表达
bioconductor-limma = "*"
bioconductor-deseq2 = "*"
# 富集
bioconductor-clusterProfiler = "*"

[feature.rnaseq.pypi-dependencies]
signatureanalyzer = "*"

[feature.common.dependencies]
snakemake = "*"
snakemake-storage-plugin-ftp = "*"
snakemake-storage-plugin-http = "*"
igv = "*"
sra-tools = "3.1.*"

[feature.dipseq.dependencies]
# 比对
bowtie2 = "*"
# 位点检测
macs2 = "*"
deeptools = "*"

[tasks]
install = {cmd = "pixi install -a"}
deploy = {cmd = "echo 'Deploy done'", depends-on = [
    "install", # install packages
    "wes_irkernel_register",
    "rna_irkernel_register",
    "mutsig2cv",
] }

[feature.data_science_py.tasks]
ipykernel_register = {cmd = "python -m ipykernel install --user --name data_science"}

[feature.wes.tasks]
mutsig2cv = {cmd = "git clone https://githubfast.com/getzlab/MutSig2CV"}
wes_irkernel_register = { cmd = "Rscript -e \"IRkernel::installspec(name = 'wes', displayname = 'WES')\""}

[feature.rnaseq.tasks]
rna_irkernel_register = { cmd = "Rscript -e \"IRkernel::installspec(name = 'rnaseq', displayname = 'RNA_Seq')\""}