[project]
name = "Multi-Omics Analysis Enviroments"
version = "0.1"
description = "Multi-Omics Analysis Enviroments"
authors = ["Sylens Wong"]
channels = ["conda-forge", "bioconda", "HCC"]
platforms = ["linux-64"]

[pypi-options]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[environments]
wes = ["qc", "wes", "r_base"]
rnaseq = ["qc", "rnaseq", "r_base"]
dipseq = ["qc", "dipseq"]
common = ["common"]
pydata = ["python3_base", "data_science_py"]

[feature.python3_base.dependencies]
python = "3.11.*"
pip = "*"
jupyter = "*"
ipykernel = "*"

[feature.r_base.dependencies]
r-base = "4.2.*"
r-irkernel = "*"
r-remotes = "*"
r-devtools = "*"

[feature.data_science_py.dependencies]
numpy = "*"
pandas = "*"
statsmodels = "*" # 统计模块
scipy = "*"

[feature.qc.dependencies]
# 质控
fastqc = "*"
fastp = "*"
multiqc = "*"

[feature.wes.dependencies]
# 比对
bwa = "*"
# 多功能
samtools = "*"
bedtools = "*"
# 突变相关
bcftools = "*"
gatk4 = "*"
ensembl-vep = "*"
snpeff = "*"
# CNV检测
CNVkit = "*"
gistic2 = { version = "*", channel = "HCC" }
# 下游展示
bioconductor-maftools = "*"

[feature.rnaseq.dependencies]
# 比对
star = "*"
hisat2 = "*"
# 表达矩阵
htseq = "*"
subread = "*"
# 差异表达
bioconductor-limma = "*"
bioconductor-deseq2 = "*"
# 富集
bioconductor-clusterProfiler = "*"

[feature.common.dependencies]
snakemake = "*"
snakemake-storage-plugin-ftp = "*"
snakemake-storage-plugin-http = "*"
igv = "*"
sra-tools = "3.1.*"

[feature.dipseq.dependencies]
# 比对
bowtie2 = "*"
# 位点检测
macs2 = "*"
deeptools = "*"

[tasks]
# install = {cmd = "pixi install -a"}
# deploy = {cmd = "echo 'Deploy done'", depends-on = [
#     "install", # install packages
#     "shapemapper_link", "annovar_link", "cellranger_link", # link uncompressed soft
#     "rlang_post_install", "python3_post_install", # install need package not found in conda/pypi
#     "kernel_register_rlang", "kernel_register_python3", "kernel_register_python2" # add jupyter kernel
# ] }

# [feature.bioinfo.tasks]
# shapemapper_dl = {cmd = "wget -O build/shapemapper2-2.2.tar.gz https://github.com/Weeks-UNC/shapemapper2/releases/download/2.2.0/shapemapper2-2.2.tar.gz", outputs = ["build/shapemapper2-2.2.tar.gz"] }
# shapemapper_untar = {cmd = "tar xvf build/shapemapper2-2.2.tar.gz -C .pixi/envs/bioinfo/share/",  inputs=["build/shapemapper2-2.2.tar.gz"]}
# shapemapper_link = {cmd = "ln -s $PWD/.pixi/envs/bioinfo/share/shapemapper2/shapemapper .pixi/envs/bioinfo/bin/shapemapper", depends-on=["shapemapper_untar"]}

# cellranger_dl = {cmd = "wget -O build/cellranger-7.2.0.tar.gz 'https://cf.10xgenomics.com/releases/cell-exp/cellranger-7.2.0.tar.gz?Expires=1718891687&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA&Signature=TpvRSQNPoCnF1PL8wK5N7lt9Vgr5tRyqRUwRNBTWMTr23KfgTPNu08yrVC6wk-0n~c8Gj2FBgvcNhSU2PTQRTqsyoEvG2R-LUhSjjVpBCdMV4v91Svs0UnIxjLvP5P7vqRGrfh5kBTa0CgW~SnLN4jveO7DY5PH~cJ-0krOTqCR76V0XKA06EAIC2u5tcJFv7kB1Pxs9VCDsAEnfu3sWmiixudORujqmg~GRk5yIyEExlC-oD~RJPbfh9EMiTumc6tAWRrbhSA0UdeL~Z~f1ZSJUqWiwCzxY5k2krrFSBI1TkhFVZf66X9Z0YDYk3S5mL6SXIllUOnsYLtjqrtnpsw__'", outputs=["build/cellranger-7.2.0.tar.gz"]}
# cellranger_untar = {cmd = "tar xvf build/cellranger-7.2.0.tar.gz -C .pixi/envs/bioinfo/share/", inputs=["build/cellranger-7.2.0.tar.gz"]}
# cellranger_link = {cmd = "ln -s $PWD/.pixi/envs/bioinfo/share/cellranger-7.2.0/cellranger .pixi/envs/bioinfo/bin/cellranger", depends-on=["cellranger_untar"]}

# [feature.rlang.tasks]
# rlang_post_install = {cmd = "Rscript rlang_post_install.r"}
# kernel_register_rlang = {cmd = "Rscript rlang_kernel.r && python -m ipykernel install --user --name rlang_py"}

# [feature.data_science.tasks]
# python3_post_install = {cmd = "pip3 install 'nbconvert[webpdf]' -i https://pypi.tuna.tsinghua.edu.cn/simple"}
# kernel_register_python3 = {cmd = "python -m ipykernel install --user --name Python3"}

# [feature.python2_base.tasks]
# kernel_register_python2 = {cmd = "python -m ipykernel install --user --name Python2"}